[package]
name = "shindan-maker"
version = "0.1.6"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Nawyjx <3373167460@qq.com>"]
documentation = "https://docs.rs/shindan-maker"
repository = "https://github.com/araea/shindan-maker"
keywords = ["shindan", "shindanmaker", "quiz", "shindan-maker"]
description = "A Rust library for interacting with Shindan Maker, the popular personality quiz service."

[dependencies]
tl = "0.7.8"
thiserror = "1.0"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
reqwest = { version = "0.12.8", features = ["cookies"] }
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
